# Generated by Django 3.2.7 on 2022-03-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='SubHead_No',
        ),
        migrations.CreateModel(
            name='Minor_Head',
            fields=[
                ('MinorHead_Code', models.IntegerField(primary_key=True, serialize=False)),
                ('Head_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allotment.major_sub_head')),
            ],
        ),
        migrations.AddField(
            model_name='scheme',
            name='MinorHead_Code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='allotment.minor_head'),
            preserve_default=False,
        ),
    ]
