# Generated by Django 3.2.7 on 2022-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_auto_20220323_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major_sub_head',
            name='SubHead_Code',
            field=models.IntegerField(default=0),
        ),
    ]
