# Generated by Django 3.2.7 on 2022-03-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0003_alter_major_sub_head_subhead_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object_head',
            unique_together={('Object_Code', 'Object_Name', 'SubScheme_Code')},
        ),
    ]
